edit_uri: 'blob/main/docs/'
site_name: Computers West
site_url: https://computerswest.org/
repo_name: dwighthubbard/computerswest
repo_url: https://github.com/dwighthubbard/computerswest
extra:
  generator: false
theme:
  # name: mkdocs
  name: material
  logo: images/cw-logo-clear8-e1711862350250.png
  favicon: images/favicon.ico
  # user_color_mode_toggle: true
  # include_sidebar: true
  icon:
    edit: material/pencil 
    view: material/eye
  features:
    - navigation.sections
    - navigation.path
    - toc.integrate
    - navigation.tabs
    - navigation.instant
    - content.action.edit
  palette:
    primary: custom

extra_css:
  - stylesheets/theme.css

markdown_extensions:
    - pymdownx.blocks.html
    - admonition
    - toc:
        permalink: true
    - footnotes
    - def_list
    - attr_list
    - md_in_html
    - pymdownx.superfences
    - pymdownx.tabbed
    - pymdownx.details
    - pymdownx.critic
    - pymdownx.keys
    - pymdownx.betterem:
        smart_enable: all

plugins:
  git-authors:
    enabled: true
    repository: dwighthubbard/computerswest
    branch: main
  # git-committers:
  #   enabled: true
  #   repository: dwighthubbard/computerswest
  #   branch: main
  git-revision-date-localized:
    enable_creation_date: true
    fallback_to_build_date: true
  search:
    enabled: true

nav:
  - Home: index.md
  - About:
      - History: about/history.md
      - Cell Phones for Soldiers: about/cell-phones-for-soldiers.md
  - Membership:
      - Membership Info: membership/index.md
      - Calendar: membership/calendar.md
      - Newsletters: membership/newsletters.md
      - Officers: membership/officers.md
      - Meeting Minutes: membership/minutes.md
      - Bylaws: membership/bylaws.md
  - Monitor Signup & Training:
      - Monitor Signup: monitor/signup.md
      - Monitor Duties: monitor/duties.md
      - "Monitor Training & Orientation": monitor/training.md
      - Monitoring Manual: monitor/manual.md
  - "Technology Support & Repair": tech-support/index.md
  - Classes:
      - Overview: classes/overview.md
      - Registration: classes/registration.md
      - FAQs: classes/faqs.md
  - Special Interest Groups:
      - Overview: sigs/overview.md
      - 3D Printing: sigs/3d-printing.md
      - All Things Apple: sigs/apple.md
      - Artificial Intelligence: sigs/ai.md
      - Streaming and Cord Cutting: sigs/streaming-cord-cutting.md
      - Flight Simulator: sigs/flight-simulator.md
      - Genealogy: sigs/genealogy.md
      - "Open Systems (Linux)": sigs/open-systems.md
      - PC Windows: sigs/windows.md
      - Video Hangouts: sigs/video-hangouts.md
  - Pay Dues: pay-dues.md
